#!/bin/bash

export RUST_BACKTRACE=1
cargo watch -c                        \
    -x "clippy --tests"               \
    -x fmt                            \
    -x "doc --document-private-items" \
    -x "test --lib"                   \
    -x "aoc $*"
