#!/bin/bash

export CARGO_BUILD_TARGET=aarch64-apple-darwin

cargo watch -c               \
    -x "clippy --tests"      \
    -x fmt                   \
    -x "test -q --lib"       \
    -x "aoc $*"
